### ISSUE TITLE
NEW: Binning and calibration

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#1]
Hi Vidartf,

thanks a lot for this GUI. It's really good. I have used it with EDS spectrum image. It works very well. I have a few suggestions for new features. I'll create one Issue per feature.

To start with, EDS data are noisy. Binning (in energy or spatially) can improve a lot PCA. A widget to bin the data and to calibrate the axes_manager would be very nice.

**Comment by vidartf** [comment]
Hi!

Good to hear that you're using it. Sorry for the fluctuating state of the repo; now that things have settled in a bit more I'll start to move more development into branches.

Regarding binning, I assume this could simply be done by an integer spinner per axis (e.g. bin axis 'x' by 2) and a button. Not sure about the calibration, but all that would be needed is to set "binned" to True, and change axis.scale to an appropriate value? Any code you can supply that I can copy and paste would be useful, and then I can maybe use it as a tutorial for how to add it as a plugin.

**Comment by pburdet** [comment]
I usually do the binning just after loading the data.

>>> s = load('raw_data/17.15.35 Drift corrected spectrum image.emi', signal_type='EDS_TEM')
>>> dim = s.axes_manager.shape
>>> s = s.rebin([dim[0], dim[1], dim[2]/4])

In some cases, my raw file does not contains calibration and I have to set it myself:

>>> axes_name = ['x', 'y']
>>> units_name = '${\mu}m$'
>>> scale = array([0.04, 0.04])
>>> for i in range(2):
>>>     s.axes_manager[i].name = axes_name[i]
>>>     s.axes_manager[i].units = units_name
>>>     s.axes_manager[i].scale = scale[i]
>>> s.axes_manager[-1].scale = 0.01
>>> s.axes_manager[-1].units = "keV"
>>> s.axes_manager[-1].offset = -0.1
>>> s.axes_manager[-1].name = 'E'

**Comment by vidartf** [comment]
@pburdet This should now be implemented in a separate branch aae6f137d39aea191e1a920f2638c4a4d59b211e. I split the implementation in two:
One widget that shows the axes (basically signal.axes_manager.show()); and one dialog that lets you rebin the signal.

**Comment by vidartf** [comment]
Hmm... I see that hyperspy.rebin does not set metadata.Signal.binned. Is this the desired behavior, or should this be added here or in hyperspy?

**Comment by pburdet** [comment]
Sure binning and calibration are two separate things. ``rebin`` and ``metadata.Signal.binned`` are two different things. Look at the following example:

        s = signals.Spectrum(range(100))
        s.axes_manager[0].scale = 0.1
        print s.integrate1D(0).data
        s.metadata.Signal.binned = True
        print s.integrate1D(0).data
        print s.sum(0).data

**Comment by vidartf** [comment]
So as far as I can see, everything is OK now?
