### ISSUE TITLE
Cannot launch HyperspyUI

### ISSUE THREAD

**Issue by jat255** [vidartf/hyperspyUI#14]
Hello,

I've been trying to give hyperspyUI another shot, as I have some other group members (that are not so familiar with Python and the command line) who may be interested in using the software so I wanted to see where it stands.

I'm having trouble getting it running, both on my main installation (Windows 8.1 with 64-bit Python 2.7.9), and on a fresh install of v0.8 of hyperspy I did in a virtual machine (Windows XP with 32-bit Python 2.7.10). Hyperspy is working fine, but I cannot get hyperspyUI to launch. On both tests, using both the command line or the desktop shortcut to run the program causes the splash screen to show, and then a flicker of a command line python window, and then nothing. Looking at the task manager, it looks like a pythonw.exe process starts up and then quickly shuts down, but there is no output to the terminal or anything that helps explain what's happening.

Any ideas on how to debug this further, or perhaps get it working?

**Comment by vidartf** [comment]
First, how to debug it: Since you're running it on windows, and the command line flickers, I'd suggest to try to run it from a command line window. Then any debug output shown in the cmd window will stay visible. If you run it via pythonw.exe, you don't get a cmd window, but then the output is piped into a file "hyperspyui.log" that is put in the same folder as "launch.py".

Secondly, for what might be wrong: I'm guessing there is an issue with a dependency. Did you use `pip install` for the package? That should fix the dependencies. If not, I'll need the program output.

**Comment by jat255** [comment]
Hi Vidar,

I got it to produce some output by running `python laynch.py`. It looks like the error is related to an import of `run_frosted` in the `pyqode.python` module:

```python
Josh@josh-S30 /cygdrive/d/UMD_Research/Software/hyperspyUI/hyperspyui
$ python launch.py
C:\Python279-x64\lib\site-packages\sklearn\pls.py:7: DeprecationWarning: This module has been moved to cross_decomposition and will be removed in 0.16
  "removed in 0.16", DeprecationWarning)
Traceback (most recent call last):
  File "launch.py", line 79, in <module>
    main()
  File "launch.py", line 64, in main
    from hyperspyui.mainwindow import MainWindow
  File "C:\Python279-x64\lib\site-packages\hyperspyui\mainwindow.py", line 16, in <module>
    from hyperspyui.mainwindowlayer5 import MainWindowLayer5, tr
  File "C:\Python279-x64\lib\site-packages\hyperspyui\mainwindowlayer5.py", line 28, in <module>
    from hyperspyui.widgets.editorwidget import EditorWidget
  File "C:\Python279-x64\lib\site-packages\hyperspyui\widgets\editorwidget.py",
line 21, in <module>
    from pyqode.python.backend.workers import run_frosted, calltips
ImportError: cannot import name run_frosted
```

I installed through `pip` and it looks like my version of that package is up to date, as far as I can tell:

```
$ pip show pyqode.python
---
Name: pyqode.python
Version: 2.6.1
Location: c:\python279-x64\lib\site-packages
Requires: jedi, pyqode.core, pyflakes, docutils, pyqode.qt, pep8
```

Any thoughts?

**Comment by jat255** [comment]
Investigating further, it looks like on my system, the `pyqode.python.backend.workers.py` has a method called `run_pyflakes` but not one called `run_frosted`. Perhaps they changed the name of it?

**Comment by vidartf** [comment]
Yeah, I suspected as much. The pyqode.python package recently changed some changes to some features that I dependend on. If you downgrade to pyqode.python version 2.5.0 instead of 2.6.1, you'll be alright.

**Comment by vidartf** [comment]
Not sure if `run_pyflakes` will work directly yet, but for now 2.5.0 works.

**Comment by jat255** [comment]
Yup, that seems to have done it. A simple:
```
pip install pyqode.python==2.5.0
```
got me up and running. Thanks for the help! This GUI is great, by the way :smile:
