### ISSUE TITLE
Accessing open data from console

### ISSUE THREAD

**Issue by jat255** [vidartf/hyperspyUI#15]
This probably isn't the right place to ask for application support, but there's no documentation, so why not? :smirk: (I'd be happy to help)

I have gotten an undergrad researcher going using Hyperspy, and it is nice for him to use hyperspyUI to do some visualization and basic investigation before digging into PCA, NMF, etc.

My question, is is there a way to access the data that is already open in the session from the console? I assume this is possible and I'm just blind, but I couldn't figure it out. This would be really useful to do some operations on the data in place and see their effect in real time.

Thanks again!

**Comment by vidartf** [comment]
There is some minor attempts at documentation in DEV-README.txt, especially
the API section should be relevant. It is however a little dated. I'll try
to update it. In the mean time:

Normally I would access the signals through either of these ways:
- `ui.get_selected_signal()` or other similarly named functions on `ui`.
- `siglist`, a pushed list that mirrors the list of signals in the data
view (tree view widget).

**Comment by jat255** [comment]
Cool! 

Thanks for the tip. Is there a way to enforce the plotted figure to update from the data? I'm just testing by zeroing out some values in my spectrum image:

```python
ui.get_selected_signal().isig[180.:] = 0
```

This works, but the change isn't observed until I drag the signal locator to a new location in the navigator.  I assume there's some redraw command that I'm missing, but I cannot seem to find it...

**Comment by vidartf** [comment]
All the plotting happens as normal for hyperspy, except that in general it is better to avoid a full replot if it can be fixed with an update. Either way: Right-clicking on a signal in the data view and selecting "Plot" ought to do it. You could also try `ui.get_selected_wrapper().update()`. That function calls `update()` on both the navigator plot and signal plot.

**Comment by jat255** [comment]
Hmm, it seems that a simple `update()` won't force the plot to update. Calling `ui.get_selected_wrapper().replot()` does work, but as you said, replotting would best be avoided. Is  there a hyperspy command to update the canvas that perhaps I'm missing?

**Comment by vidartf** [comment]
If its just the canvas that needs to be redrawn then
`signal._plot.signal/navigator_plot.figure.canvas.draw()` will work, but if
that's all that was needed update should work as well. How would you do it
in hyperspy normally?

**Comment by jat255** [comment]
Thanks for the quick reply. 

I think I actually just figured this out on my own. I haven't done too much scripted updating of hyperspy plots, so I'm a little out of my limited expertise. However, running the following code does seem to force the plot to update, and you get an immediate response, as might be expected:

```python
ui.get_selected_signal().isig[120.:140.] = 0
ui.get_selected_signal()._plot.signal_plot.update()
```
