### ISSUE TITLE
Mangled Toolbar icons on Linux

### ISSUE THREAD

**Issue by jat255** [vidartf/hyperspyUI#16]
As I was playing around with HyperspyUI today on my laptop, I noticed that some icons didn't look as expected, and were cut off on the edges, namely the text ones (see below).

![icon_snapshot1](https://cloud.githubusercontent.com/assets/1278301/8946014/a3a99d4e-355a-11e5-9a35-be4ea5681f34.png)

After playing around with this, I discovered that it is due to the Calibri font (which is saved in the .svg files) is not present on Linux, so the font gets substituted in a less than ideal manner.

Searching around online, there are a few options for fixing this and having a truly "cross-platform" font. The font can be embedded in the qt resources, but this seems like it is an undesirable setup. The other option would be to either convert all the text entries in the .svg files to paths (so there is no text rendered by qt), or to use a font that is very likely to be present on all systems.

**Comment by vidartf** [comment]
I know, I've tried saving as compound paths, but I still get clipping as
well on Windows. Either way Qt should resize the icon to fit the allocated
size. I think I might have to go over the Qt SVG code I use a bit more
carefully...
