### ISSUE TITLE
NEW: X-ray lines

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#2]
Plotting the element maps works nicely. It would be nice to select the X-ray lines chosen to plot it.

Labeling X-ray lines would be great as done with marker in branch #296 of hyperspy.

**Comment by vidartf** [comment]
Off my computer now, but quickly: This should already be possible by right
clicking on the elements in the picker. Let me know if it works/not!

**Comment by pburdet** [comment]
It does work. Great!

**Comment by vidartf** [comment]
PS: With your marker branch, are the labels added automatically, or do they require extra action? If it was automatic (e.g. decided by flag on EDS signal class), then all that would be needed in UI is a check box ("Show labels"). If not automatic, then it would also need a toggle function, and a function to check whether the markers are available in hyperspy. Could you possibly supply them?

**Comment by pburdet** [comment]
It is automatic: by default the function ``plot_xray_lines`` read the X-ray lines set in metadata.Sample.Xraylines and plot the markers at the right position.

**Comment by vidartf** [comment]
Ah, so ```signal.plot()``` behaves as before, and then ```plot_xray_lines``` adds the markers to the existing plot?

**Comment by pburdet** [comment]
``s.plot_xray_lines`` called ``s.plot`` and add the markers to ``s._plot.signal_plot``. 

Adding markers work as follow:

    >>> s = signals.Spectrum(random.random([10,100]))
    >>> m = utils.plot.marker()
    >>> m.type = 'axvline'
    >>> m.set_marker_properties(color='green')
    >>> m.set_data(x1=range(10))
    >>> s.plot()
    >>> s._plot.signal_plot.add_marker(m)
    >>> m.plot()

**Comment by pburdet** [comment]
For images:

    >>> im = signals.Image(random.random([10,50,50]))
    >>> m = utils.plot.marker()
    >>> m.type = 'text'
    >>> m.set_marker_properties(fontsize = 30,color='red')
    >>> m.set_data(x1=range(10),y1=range(10)[::-1],text='hello')
    >>> im.plot()
    >>> im._plot.signal_plot.add_marker(m)
    >>> m.plot()


    >>> im = signals.Image(np.zeros((100,100)))
    >>> m = utils.plot.marker()
    >>> m.type = 'rect'
    >>> m.set_marker_properties(linewidth=4,color='red',ls='dotted')
    >>> m.set_data(x1=20,x2=70,y1=20,y2=70)
    >>> im.plot()
    >>> im._plot.signal_plot.add_marker(m)
    >>> m.plot()

**Comment by pburdet** [comment]
After merging pburdet/hyperspy/ENH_plot_Xray_lines with vidartf/hyperspy/work_horse, I tried the following code in the console and it works

s = siglist[0].signal
s.plot_xray_lines()

**Comment by pburdet** [comment]
![capture](https://cloud.githubusercontent.com/assets/3855190/5662239/7a3e63b0-972e-11e4-8a06-6fd6af427c5f.PNG)

**Comment by vidartf** [comment]
Neat, but I try to avoid replotting as much as possible (lose a lot of stuff on replot + it can be very slow), so I think the best would be to add the lines as needed (I'd have to replicate some of the functionality of ```plot_xray_lines```).

BTW: What is the best way to remove the markers for a given x-ray line from a plot? Search through the marker text of the ```signal.markers``` collection, then do ```marker.close()```, and ```signal.markers.remove(marker)```?

**Comment by pburdet** [comment]
I'll write it like that

[m.close() for m in s._plot.signal_plot.ax_markers]
[s._plot.signal_plot.ax_markers.remove(m) for m in s._plot.signal_plot.ax_markers]

**Comment by vidartf** [comment]
Implemented in #7.
