### ISSUE TITLE
NEW: recorder

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#5]
In parallel with the console, having a script recorder would be great.

**Comment by vidartf** [comment]
Yeah, in principle what I had planned here was to make an editor/recorder that creates a plugin. The code would be wrapped in a function, and then an action would be created given user input (label and optionally description and icon). Then there should be two check boxes so the user can select "add to menu/toolbar".
Recording things from the console should be easy; recording actions (toolbar/menu single clicks) should be somewhat easy; recording interactive tools/widgets would be more tricky (would require faculty for tools/widgets to record and replay history).

**Comment by pburdet** [comment]
Sounds promising

**Comment by vidartf** [comment]
Fixed in cd89636bd4985782f6c27e46da2a492a4b156fb3.

**Comment by vidartf** [comment]
PS: In case the warnings were not enough: You need to install pyqode.core to get the recorder UI.
