### ISSUE TITLE
BUG: FFT FFT-1

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#6]
The inverse FFT of an FFT does no give the actual image

![capture](https://cloud.githubusercontent.com/assets/3855190/5661134/fea8ac64-971f-11e4-8424-6a99cede88d0.PNG)

It would be nice to have FFT implemented in hyperspy as discussed in hyperspy/hyperspy#117. I have started a branch https://github.com/pburdet/hyperspy/tree/image_FFT some times ago. Does this correspond to what you have done in hyperspyUI?

**Comment by vidartf** [comment]
This should now be fixed on master.
