### ISSUE TITLE
Which version of Hyperspy should we use?

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#9]
Currently the version of hyperspy needed to make the UI work is vidartf/work_house. Should there be a branch on hyperspy repository that works with the current version of the UI?

**Comment by vidartf** [comment]
I try to make it so that hyperspy/master can always be used with hyperspyui/master. Some functionality might be disabled, but at least everything that loads should work. However, everything is still pretty rough, so there might be some glitches :)
